//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class CentrosAsistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentrosAsistencia()
        {
            this.VacunasxCiudadanoes = new HashSet<VacunasxCiudadano>();
        }

        public int Id_Asistencia { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> Capacidad_Atencion { get; set; }
        public Nullable<int> Cantidad_Medicos { get; set; }
        public Nullable<int> Cantidad_Enfermeras { get; set; }
        public string Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacunasxCiudadano> VacunasxCiudadanoes { get; set; }
    }
}
