//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudadano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciudadano()
        {
            this.VacunasxCiudadanoes = new HashSet<VacunasxCiudadano>();
        }
    
        public int Id_Ciudadanos { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public string Telefono { get; set; }
        public string Direccion_Domicilio { get; set; }
        public string Estado_Civil { get; set; }
        public string Enfermedades_Base { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacunasxCiudadano> VacunasxCiudadanoes { get; set; }
    }
}
