//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Codigo { get; set; }
        public string Contraseña { get; set; }
        public string NumeroIdentidad { get; set; }
        public string NombreCompleto { get; set; }
        public string Genero { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Rol { get; set; }
    }
}
