//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacunasxCiudadano
    {
        public int Numero_Dosis { get; set; }
        public int Ciudadano_ID { get; set; }
        public int Centro_Asistencia_ID { get; set; }
        public int Codigo_Vacuna { get; set; }
        public Nullable<System.DateTime> Fecha_Aplicacion { get; set; }
        public virtual CentrosAsistencia CentrosAsistencia { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual Vacuna Vacuna { get; set; }
    }
}
